### PR TITLE
Added color support for 0.16

### PR DESCRIPTION
**Pull request by Fresheyeball**
#21

### CODE REVIEW

**Comment by Fresheyeball** [comment]
screenshot from 2015-12-13 17 29 03

->

screenshot from 2015-12-13 17 27 59

**Comment by mrmurphy** [comment]
This looks neat, @Fresheyeball 
@mybuddymichael have you been too busy recently to review these PRs? I'd love to see some of these changes merged in without forking the repo and doing it on my own version.

Thanks!

**Comment by mybuddymichael** [comment]
Oh man, @splodingsocks, thanks for bringing this to my attention. I thought I was watching all my repos, but, for some reason, I wasn't watching this one. I had no idea all these issues and PRs had been created. :flushed:

I'm now watching this and, yes, I'll definitely sort through all these and get them merged as I can.

**Comment by mrmurphy** [comment]
Great! I'm so excited to start using this plugin again, @mybuddymichael ! Thanks for your work!

**Comment by mybuddymichael** [comment]
@splodingsocks I haven't been able to get around to reviewing these, so you and @thSoft now have collaborator privileges, if either of you have the time to review and merge as needed.

**Comment by mrmurphy** [comment]
@mybuddymichael awesome, thanks!

**Comment by mrmurphy** [comment]
@mybuddymichael you're the only one who can make a new release, right?

**Comment by mybuddymichael** [comment]
@splodingsocks I have no idea. I assume you tried and it won't let you?

**Comment by Fresheyeball** [comment]
Hurray!

**Comment by mrmurphy** [comment]
@mybuddymichael just checked, looks like I'm able to publish a package version too!

**Pull request merged**
