### PR TITLE
Fix #11

### LINKED ISSUE #11: Works only when packages are installed
Linting fails silently when run with a project whose packages are not yet installed.

### PR DESCRIPTION
**Pull request by thSoft**

### CODE REVIEW

**Comment by mrmurphy** [comment]
Does this one overlap with https://github.com/mybuddymichael/linter-elm-make/pull/15? Looks like they share some changes.

**Comment by thSoft** [comment]
Yes, it only adds cadf42d on top of this.

**Comment by mrmurphy** [comment]
Looks good then, after a rebase

**Comment by mrmurphy** [comment]
Thanks for making all of these changes, @thSoft !

**Pull request merged**
