### PR TITLE
Fix #16

### LINKED ISSUE #16: Show visual feedback on linting in progress
It would be great if something indicated visually that the linting process is running.

### PR DESCRIPTION
**Pull request by thSoft**

### CODE REVIEW

**Comment by thSoft** [comment]
Unfortunately this conflicts with #12 & #15; if you merge them, I'd gladly rebase this on top of them.

**Comment by mrmurphy** [comment]
For convenience: https://github.com/mybuddymichael/linter-elm-make/issues/16

**Comment by thSoft** [comment]
@splodingsocks: the link to the issue in the commit link also works. :)

**Comment by mrmurphy** [comment]
I just noticed that! Thanks :)

**Comment by thSoft** [comment]
@Fresheyeball, @splodingsocks, could you review my PRs so I can merge them confidently? Thanks!

**Comment by mrmurphy** [comment]
:+1:

**Comment by mrmurphy** [comment]
This one looks good to me.

**Pull request merged**
